base_url = "https://tayi.netlify.app/"

default_language = "en"
compile_sass = true
title = "台一工程行"
description = "專精於在建工程。"
generate_feed = false
output_dir = "docs"

taxonomies = [
  {name = "tags", paginate_by = 5},
  {name = "authors", paginate_by = 5},
]

build_search_index = true

[markdown]
highlight_code = true

[extra]
banner = "img/banner.jpeg"
date_format = '%d/%m/%Y'

theme = 'simplex'
bg = "dark"
inverted = false

#themes = "Choose a Theme"
#schemes = "Choose a Color Scheme"
search = 'Search'
tag = 'Posts by Topic'
tags = 'Posts by Topics'

links = [apple
	{title = '工程實績', url = 'articles'},
  {title = '聯絡我們', url = 'authors'},
	{title = '關於台一', url = 'about'},
  #{title = '實績案例', url = 'about'},
	#{title = 'Topics', url = 'tags'},
	#{title = 'Github', url = 'https://github.com/marcodpt/zolastrap'},
]
email = "610101apple@mail.com"
icons = [
  {title = 'Facebook', icon = 'facebook-f', url = 'https://www.facebook.com'},
  {title = 'Instagram', icon = 'instagram', url = 'https://www.instagram.com'},
  {title = 'Twitter', icon = 'twitter', url = 'https://twitter.com'},
  {title = 'YouTube', icon = 'youtube', url = 'https://www.youtube.com'}
]

utterances = ""
utterances_label = "Comments"
utterances_theme = "github-light"
utterances_issue_term = "pathname"

# Do not change this variables
data_themes = [
  'default',
  'cerulean',
  'cosmo',
  'cyborg',
  'darkly',
  'flatly',
  'journal',
  'litera',
  'lumen',
  'lux',
  'materia',
  'minty',
  'morph',
  'pulse',
  'quartz',
  'sandstone',
  'simplex',
  'sketchy',
  'slate',
  'solar',
  'spacelab',
  'superhero',
  'united',
  'vapor',
  'yeti',
  'zephyr'
]
data_schemes = [
  'dark',
  'light',
  'primary',
  'primary inverted',
  'secondary',
  'secondary inverted',
  'success',
  'success inverted',
  'danger',
  'danger inverted',
  'warning',
  'warning inverted',
  'info',
  'info inverted',
]
